server:
  port: ${PORT:8080}

spring:
  application:
    name: register-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/register}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/register}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    locations: classpath:db/migration
