apiVersion: v1
kind: Service
metadata:
  name: register-service
spec:
  type: LoadBalancer
  selector:
    app: register-service-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  externalTrafficPolicy: Local